### PR TITLE
Add "show source" button

### PR DESCRIPTION
**Pull request by Tarpsvo**
Heya!

One of my must-haves was a possibility to copy, paste and edit HTML source. I added a plugin for that.

Also added SupportsDependentFields trait to the field so its visibility etc can be toggled using ->dependsOn() in Nova.

### CODE REVIEW

**Review by JacobFitzp — APPROVED** [review]
Works a treat thank you for contributing 🙂

**Comment by Tarpsvo** [comment]
There was an error though - I wasn't able to get the active() flag to work. It doesn't seem to update and will never re-color the icon. I tried a dozen different ways, but couldn't get it to the recompute correctly. I have no idea why the "editor.isActive()" in other tools updates it as expected, but returning a boolean does not.

**Comment by JacobFitzp** [comment]
Yeah I noticed that, not the end of the world. I will see if I can get something working before I do a release 🙂

**Comment by JacobFitzp** [comment]
I got this working use Vue `ref`

https://github.com/user-attachments/assets/981ca01b-91ff-4243-bd35-69c34caeb0a9

**Pull request merged**
